name: drag_drop
version: 1.2.0
dependencies:
  browser_detect:
    git: git@github.com:danschultz/browser_detect.dart.git
  logging: '>=0.5.13'
dev_dependencies:
  browser: any
  js: any
  unittest: 0.5.5
